[2021-09-17 16:48:29] INFO "POST /login/ HTTP/1.1" 200 58
[2021-09-17 16:48:37] INFO checkuserlevel
[2021-09-17 16:48:37] INFO "POST /login/ HTTP/1.1" 200 58
[2021-09-17 16:48:46] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:48:48] INFO Watching for file changes with StatReloader
[2021-09-17 16:48:50] INFO "POST /login/ HTTP/1.1" 200 58
[2021-09-17 16:49:10] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:49:13] INFO Watching for file changes with StatReloader
[2021-09-17 16:49:31] INFO /home/m0nd2y/paybag-server/paybag_api/main/urls.py changed, reloading.
[2021-09-17 16:49:32] INFO Watching for file changes with StatReloader
[2021-09-17 16:49:46] INFO /home/m0nd2y/paybag-server/paybag_api/paybag_api/settings.py changed, reloading.
[2021-09-17 16:49:47] INFO Watching for file changes with StatReloader
[2021-09-17 16:50:10] INFO "POST /login/ HTTP/1.1" 200 58
[2021-09-17 16:50:13] INFO "POST /login/ HTTP/1.1" 200 58
[2021-09-17 16:51:11] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:51:13] INFO Watching for file changes with StatReloader
[2021-09-17 16:51:28] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:51:29] INFO Watching for file changes with StatReloader
[2021-09-17 16:51:36] WARNING Bad Request: /login/
[2021-09-17 16:51:36] WARNING "POST /login/ HTTP/1.1" 400 0
[2021-09-17 16:51:45] WARNING Bad Request: /login/
[2021-09-17 16:51:45] WARNING "POST /login/ HTTP/1.1" 400 0
[2021-09-17 16:51:51] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:51:52] INFO Watching for file changes with StatReloader
[2021-09-17 16:51:54] WARNING Bad Request: /login/
[2021-09-17 16:51:54] WARNING "POST /login/ HTTP/1.1" 400 0
[2021-09-17 16:52:02] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:52:04] INFO Watching for file changes with StatReloader
[2021-09-17 16:52:06] INFO "POST /login/ HTTP/1.1" 200 58
[2021-09-17 16:52:15] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:52:17] INFO Watching for file changes with StatReloader
[2021-09-17 16:52:19] WARNING Bad Request: /login/
[2021-09-17 16:52:19] WARNING "POST /login/ HTTP/1.1" 400 0
[2021-09-17 16:52:21] WARNING Bad Request: /login/
[2021-09-17 16:52:21] WARNING "POST /login/ HTTP/1.1" 400 0
[2021-09-17 16:52:34] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:52:36] INFO Watching for file changes with StatReloader
[2021-09-17 16:52:43] WARNING Bad Request: /login/
[2021-09-17 16:52:43] WARNING "POST /login/ HTTP/1.1" 400 0
[2021-09-17 16:53:15] WARNING Bad Request: /login/
[2021-09-17 16:53:15] WARNING "POST /login/ HTTP/1.1" 400 0
[2021-09-17 16:53:16] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:53:18] INFO Watching for file changes with StatReloader
[2021-09-17 16:53:19] WARNING Bad Request: /login/
[2021-09-17 16:53:19] WARNING "POST /login/ HTTP/1.1" 400 0
[2021-09-17 16:53:28] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:53:30] INFO Watching for file changes with StatReloader
[2021-09-17 16:53:33] WARNING Bad Request: /login/
[2021-09-17 16:53:33] WARNING "POST /login/ HTTP/1.1" 400 0
[2021-09-17 16:53:54] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:53:56] INFO Watching for file changes with StatReloader
[2021-09-17 16:54:29] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:54:30] INFO Watching for file changes with StatReloader
[2021-09-17 16:54:32] WARNING Bad Request: /login/
[2021-09-17 16:54:32] WARNING "POST /login/ HTTP/1.1" 400 0
[2021-09-17 16:54:33] WARNING Bad Request: /login/
[2021-09-17 16:54:33] WARNING "POST /login/ HTTP/1.1" 400 0
[2021-09-17 16:55:14] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:55:16] INFO Watching for file changes with StatReloader
[2021-09-17 16:55:22] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:55:24] INFO Watching for file changes with StatReloader
[2021-09-17 16:55:27] INFO login
[2021-09-17 16:55:27] INFO "POST /login/ HTTP/1.1" 200 58
[2021-09-17 16:55:35] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:55:37] INFO Watching for file changes with StatReloader
[2021-09-17 16:55:39] WARNING Bad Request: /login/
[2021-09-17 16:55:39] WARNING "POST /login/ HTTP/1.1" 400 0
[2021-09-17 16:55:48] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:55:49] INFO Watching for file changes with StatReloader
[2021-09-17 16:55:56] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:55:59] INFO Watching for file changes with StatReloader
[2021-09-17 16:56:01] ERROR Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/paybag-server/paybag_api/main/views.py", line 93, in login
    logging.info("login" + data)
TypeError: can only concatenate str (not "dict") to str
[2021-09-17 16:56:01] ERROR "POST /login/ HTTP/1.1" 500 95064
[2021-09-17 16:56:03] ERROR Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/paybag-server/paybag_api/main/views.py", line 93, in login
    logging.info("login" + data)
TypeError: can only concatenate str (not "dict") to str
[2021-09-17 16:56:03] ERROR "POST /login/ HTTP/1.1" 500 95064
[2021-09-17 16:56:30] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:56:32] INFO Watching for file changes with StatReloader
[2021-09-17 16:56:35] ERROR Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/paybag-server/paybag_api/main/views.py", line 93, in login
    logging.info("login" + eval(data))
TypeError: eval() arg 1 must be a string, bytes or code object
[2021-09-17 16:56:35] ERROR "POST /login/ HTTP/1.1" 500 95058
[2021-09-17 16:56:37] ERROR Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/paybag-server/paybag_api/main/views.py", line 93, in login
    logging.info("login" + eval(data))
TypeError: eval() arg 1 must be a string, bytes or code object
[2021-09-17 16:56:37] ERROR "POST /login/ HTTP/1.1" 500 95058
[2021-09-17 16:57:11] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:57:12] INFO Watching for file changes with StatReloader
[2021-09-17 16:57:14] INFO login{'phone': '01092939495', 'password': 'qwer1234'}
[2021-09-17 16:57:14] INFO "POST /login/ HTTP/1.1" 200 58
[2021-09-17 16:57:26] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:57:28] INFO Watching for file changes with StatReloader
[2021-09-17 16:57:33] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:57:35] INFO Watching for file changes with StatReloader
[2021-09-17 16:57:37] INFO [login] {'phone': '01092939495', 'password': 'qwer1234'}
[2021-09-17 16:57:37] INFO "POST /login/ HTTP/1.1" 200 58
[2021-09-17 16:57:43] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:57:44] INFO Watching for file changes with StatReloader
[2021-09-17 16:57:46] INFO "POST /login/ HTTP/1.1" 200 58
[2021-09-17 16:57:50] INFO "POST /login/ HTTP/1.1" 200 58
[2021-09-17 16:58:00] INFO "POST /login/ HTTP/1.1" 200 58
[2021-09-17 16:59:09] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:59:11] INFO Watching for file changes with StatReloader
[2021-09-17 16:59:15] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:59:17] INFO Watching for file changes with StatReloader
[2021-09-17 16:59:19] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:59:21] INFO Watching for file changes with StatReloader
[2021-09-17 16:59:25] WARNING Bad Request: /login/
[2021-09-17 16:59:25] WARNING "POST /login/ HTTP/1.1" 400 0
[2021-09-17 16:59:39] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 16:59:41] INFO Watching for file changes with StatReloader
[2021-09-17 16:59:43] INFO "POST /login/ HTTP/1.1" 200 58
[2021-09-17 16:59:59] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:00:02] INFO Watching for file changes with StatReloader
[2021-09-17 17:00:04] INFO "POST /login/ HTTP/1.1" 200 58
[2021-09-17 17:00:07] INFO "POST /login/ HTTP/1.1" 200 58
[2021-09-17 17:00:13] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:00:16] INFO Watching for file changes with StatReloader
[2021-09-17 17:00:19] INFO [login] {'phone': '01092939495', 'password': 'qwer1234'}
[2021-09-17 17:00:19] INFO "POST /login/ HTTP/1.1" 200 58
[2021-09-17 17:01:35] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:01:37] INFO Watching for file changes with StatReloader
[2021-09-17 17:02:14] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:02:16] INFO Watching for file changes with StatReloader
[2021-09-17 17:02:40] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:02:42] INFO Watching for file changes with StatReloader
[2021-09-17 17:02:51] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:02:54] INFO Watching for file changes with StatReloader
[2021-09-17 17:02:56] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:02:58] INFO Watching for file changes with StatReloader
[2021-09-17 17:03:01] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:03:03] INFO Watching for file changes with StatReloader
[2021-09-17 17:04:26] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:04:29] INFO Watching for file changes with StatReloader
[2021-09-17 17:04:58] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:05:00] INFO Watching for file changes with StatReloader
[2021-09-17 17:05:06] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:05:09] INFO Watching for file changes with StatReloader
[2021-09-17 17:05:19] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:05:22] INFO Watching for file changes with StatReloader
[2021-09-17 17:05:32] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:05:35] INFO Watching for file changes with StatReloader
[2021-09-17 17:05:37] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:05:39] INFO Watching for file changes with StatReloader
[2021-09-17 17:05:41] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:05:42] INFO Watching for file changes with StatReloader
[2021-09-17 17:06:02] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:06:05] INFO Watching for file changes with StatReloader
[2021-09-17 17:06:59] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:07:01] INFO Watching for file changes with StatReloader
[2021-09-17 17:07:48] INFO [market] request market data
[2021-09-17 17:07:48] INFO "GET /market/ HTTP/1.1" 200 1071
[2021-09-17 17:08:27] INFO [history] request history data
[2021-09-17 17:08:27] INFO "GET /history/ HTTP/1.1" 200 1760
[2021-09-17 17:08:59] INFO [history] request history data
[2021-09-17 17:08:59] INFO "GET /history/ HTTP/1.1" 200 1760
[2021-09-17 17:09:17] INFO [history] request history data
[2021-09-17 17:09:17] INFO "GET /history/ HTTP/1.1" 200 1760
[2021-09-17 17:09:54] INFO [history] request history data
[2021-09-17 17:09:54] INFO "GET /history/ HTTP/1.1" 200 1760
[2021-09-17 17:10:25] INFO [history] request history data
[2021-09-17 17:10:25] INFO "GET /history/ HTTP/1.1" 200 1760
[2021-09-17 17:11:51] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:11:54] INFO Watching for file changes with StatReloader
[2021-09-17 17:11:57] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:12:00] INFO Watching for file changes with StatReloader
[2021-09-17 17:12:09] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:12:12] INFO Watching for file changes with StatReloader
[2021-09-17 17:12:49] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:12:51] INFO Watching for file changes with StatReloader
[2021-09-17 17:12:54] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:12:57] INFO Watching for file changes with StatReloader
[2021-09-17 17:13:07] INFO "GET /admin/main/user/ HTTP/1.1" 200 8449
[2021-09-17 17:13:08] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 17:13:09] INFO "GET /admin/main/history/ HTTP/1.1" 200 8521
[2021-09-17 17:13:10] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 17:13:11] INFO "GET /admin/main/history/8/change/ HTTP/1.1" 200 9293
[2021-09-17 17:13:11] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 17:13:17] INFO "GET /admin/main/user/ HTTP/1.1" 200 8449
[2021-09-17 17:13:17] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 17:13:19] INFO "GET /admin/main/user/2/change/ HTTP/1.1" 200 11522
[2021-09-17 17:13:20] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 17:13:39] INFO "GET /history HTTP/1.1" 301 0
[2021-09-17 17:13:40] ERROR Internal Server Error: /history/
Traceback (most recent call last):
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/paybag-server/paybag_api/main/views.py", line 202, in history
    data = JSONParser().parse(requests)
NameError: name 'requests' is not defined
[2021-09-17 17:13:40] ERROR "GET /history/ HTTP/1.1" 500 94467
[2021-09-17 17:14:01] INFO "GET /history HTTP/1.1" 301 0
[2021-09-17 17:14:02] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:14:05] INFO Watching for file changes with StatReloader
[2021-09-17 17:14:08] INFO "GET /history HTTP/1.1" 301 0
[2021-09-17 17:14:08] WARNING Bad Request: /history/
[2021-09-17 17:14:08] WARNING "GET /history/ HTTP/1.1" 400 73
[2021-09-17 17:14:17] INFO "GET /history HTTP/1.1" 301 0
[2021-09-17 17:14:18] WARNING Bad Request: /history/
[2021-09-17 17:14:18] WARNING "GET /history/ HTTP/1.1" 400 73
[2021-09-17 17:15:02] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:15:05] INFO Watching for file changes with StatReloader
[2021-09-17 17:15:08] INFO "GET /history HTTP/1.1" 301 0
[2021-09-17 17:15:09] WARNING Bad Request: /history/
[2021-09-17 17:15:09] WARNING "GET /history/ HTTP/1.1" 400 73
[2021-09-17 17:15:14] WARNING Bad Request: /history/
[2021-09-17 17:15:14] WARNING "GET /history/ HTTP/1.1" 400 73
[2021-09-17 17:15:19] INFO - Broken pipe from ('61.82.101.19', 50576)

[2021-09-17 17:15:25] INFO "GET /history HTTP/1.1" 301 0
[2021-09-17 17:15:26] WARNING Bad Request: /history/
[2021-09-17 17:15:26] WARNING "GET /history/ HTTP/1.1" 400 73
[2021-09-17 17:15:51] INFO "GET /history?phone=01092920303 HTTP/1.1" 301 0
[2021-09-17 17:15:51] WARNING Bad Request: /history/
[2021-09-17 17:15:51] WARNING "GET /history/?phone=01092920303 HTTP/1.1" 400 73
[2021-09-17 17:15:58] INFO "GET /history HTTP/1.1" 301 0
[2021-09-17 17:15:59] WARNING Bad Request: /history/
[2021-09-17 17:15:59] WARNING "GET /history/ HTTP/1.1" 400 73
[2021-09-17 17:16:00] INFO "GET /history HTTP/1.1" 301 0
[2021-09-17 17:16:00] WARNING Bad Request: /history/
[2021-09-17 17:16:00] WARNING "GET /history/ HTTP/1.1" 400 73
[2021-09-17 17:16:04] INFO "GET /admin/main/user/ HTTP/1.1" 200 8449
[2021-09-17 17:16:51] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:16:53] INFO Watching for file changes with StatReloader
[2021-09-17 17:16:57] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:16:59] INFO Watching for file changes with StatReloader
[2021-09-17 17:17:04] INFO "GET /history?phone=1234 HTTP/1.1" 301 0
[2021-09-17 17:17:05] INFO [history] <QueryDict: {'phone': ['1234']}>
[2021-09-17 17:17:05] ERROR Internal Server Error: /history/
Traceback (most recent call last):
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/paybag-server/paybag_api/main/views.py", line 204, in history
    user = User.objects.get(phone = search_phone)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
main.models.User.DoesNotExist: User matching query does not exist.
[2021-09-17 17:17:05] ERROR "GET /history/?phone=1234 HTTP/1.1" 500 104209
[2021-09-17 17:17:13] INFO "GET /history?phone=01092920303 HTTP/1.1" 301 0
[2021-09-17 17:17:13] INFO [history] <QueryDict: {'phone': ['01092920303']}>
[2021-09-17 17:17:13] ERROR Internal Server Error: /history/
Traceback (most recent call last):
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/paybag-server/paybag_api/main/views.py", line 204, in history
    user = User.objects.get(phone = search_phone)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
main.models.User.MultipleObjectsReturned: get() returned more than one User -- it returned 2!
[2021-09-17 17:17:13] ERROR "GET /history/?phone=01092920303 HTTP/1.1" 500 104485
[2021-09-17 17:17:33] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:17:35] INFO Watching for file changes with StatReloader
[2021-09-17 17:17:38] INFO "GET /history?phone=01092920303 HTTP/1.1" 301 0
[2021-09-17 17:17:38] INFO [history] <QueryDict: {'phone': ['01092920303']}>
[2021-09-17 17:17:38] ERROR Internal Server Error: /history/
Traceback (most recent call last):
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/paybag-server/paybag_api/main/views.py", line 205, in history
    user = User.objects.get(phone = search_phone)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
main.models.User.MultipleObjectsReturned: get() returned more than one User -- it returned 2!
[2021-09-17 17:17:38] ERROR "GET /history/?phone=01092920303 HTTP/1.1" 500 104468
[2021-09-17 17:17:56] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:17:58] INFO Watching for file changes with StatReloader
[2021-09-17 17:18:02] INFO "GET /admin/main/user/ HTTP/1.1" 200 8449
[2021-09-17 17:18:02] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 17:18:07] INFO "GET /history?phone=01046156192 HTTP/1.1" 301 0
[2021-09-17 17:18:08] INFO [history] <QueryDict: {'phone': ['01046156192']}>
[2021-09-17 17:18:08] ERROR Internal Server Error: /history/
Traceback (most recent call last):
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/paybag-server/paybag_api/main/views.py", line 204, in history
    user = User.objects.get(phone = search_phone)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
main.models.User.DoesNotExist: User matching query does not exist.
[2021-09-17 17:18:08] ERROR "GET /history/?phone=01046156192 HTTP/1.1" 500 104335
[2021-09-17 17:18:14] INFO "GET /admin/main/user/2/change/ HTTP/1.1" 200 11522
[2021-09-17 17:18:14] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 17:18:16] INFO "GET /admin/main/user/ HTTP/1.1" 200 8449
[2021-09-17 17:18:17] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 17:18:17] INFO "GET /admin/main/history/8/change/ HTTP/1.1" 200 9293
[2021-09-17 17:18:17] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 17:18:18] INFO "GET /admin/main/history/ HTTP/1.1" 200 8521
[2021-09-17 17:18:19] INFO "GET /admin/main/history/8/change/ HTTP/1.1" 200 9293
[2021-09-17 17:18:20] INFO "GET /admin/main/history/ HTTP/1.1" 200 8521
[2021-09-17 17:18:23] INFO "GET /admin/main/user/ HTTP/1.1" 200 8449
[2021-09-17 17:18:24] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 17:18:25] INFO "GET /admin/main/user/1/change/ HTTP/1.1" 200 11558
[2021-09-17 17:18:25] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 17:18:30] INFO "GET /history?phone=01012345678 HTTP/1.1" 301 0
[2021-09-17 17:18:31] INFO [history] <QueryDict: {'phone': ['01012345678']}>
[2021-09-17 17:18:31] INFO "GET /history/?phone=01012345678 HTTP/1.1" 200 746
[2021-09-17 17:18:53] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:18:55] INFO Watching for file changes with StatReloader
[2021-09-17 17:24:17] INFO [market] request market data
[2021-09-17 17:24:17] INFO "GET /market/ HTTP/1.1" 200 1071
[2021-09-17 17:24:23] ERROR Internal Server Error: /history/
Traceback (most recent call last):
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'phone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/paybag-server/paybag_api/main/views.py", line 202, in history
    search_phone = request.GET['phone']
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'phone'
[2021-09-17 17:24:23] ERROR "GET /history/ HTTP/1.1" 500 103167
[2021-09-17 17:35:47] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:35:49] INFO Watching for file changes with StatReloader
[2021-09-17 17:39:48] INFO /home/m0nd2y/paybag-server/paybag_api/main/urls.py changed, reloading.
[2021-09-17 17:39:49] INFO Watching for file changes with StatReloader
[2021-09-17 17:40:50] INFO [market] request market data
[2021-09-17 17:40:50] INFO "GET /market/ HTTP/1.1" 200 1071
[2021-09-17 17:41:03] INFO [market] request market data
[2021-09-17 17:41:03] INFO "GET /market/ HTTP/1.1" 200 1071
[2021-09-17 17:41:08] INFO "GET /market HTTP/1.1" 301 0
[2021-09-17 17:41:08] INFO [market] request market data
[2021-09-17 17:41:08] INFO "GET /market/ HTTP/1.1" 200 1071
[2021-09-17 17:41:21] INFO - Broken pipe from ('61.82.101.19', 57087)

[2021-09-17 17:41:24] INFO [market] request market data
[2021-09-17 17:41:24] INFO "GET /market/ HTTP/1.1" 200 1071
[2021-09-17 17:41:25] INFO "GET /history HTTP/1.1" 301 0
[2021-09-17 17:41:26] ERROR Internal Server Error: /history/
Traceback (most recent call last):
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'phone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/paybag-server/paybag_api/main/views.py", line 186, in history
    search_phone = request.GET['phone']
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'phone'
[2021-09-17 17:41:26] ERROR "GET /history/ HTTP/1.1" 500 103167
[2021-09-17 17:41:33] ERROR Internal Server Error: /history/
Traceback (most recent call last):
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'phone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/paybag-server/paybag_api/main/views.py", line 186, in history
    search_phone = request.GET['phone']
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'phone'
[2021-09-17 17:41:33] ERROR "GET /history/ HTTP/1.1" 500 103167
[2021-09-17 17:41:48] INFO - Broken pipe from ('61.82.101.19', 57100)

[2021-09-17 17:42:00] INFO "GET /history?phone=01052376809 HTTP/1.1" 301 0
[2021-09-17 17:42:01] INFO [history] <QueryDict: {'phone': ['01052376809']}>
[2021-09-17 17:42:01] INFO "GET /history/?phone=01052376809 HTTP/1.1" 200 2
[2021-09-17 17:43:19] INFO [market] request market data
[2021-09-17 17:43:19] INFO "GET /market/ HTTP/1.1" 200 1071
[2021-09-17 17:43:22] INFO "GET /history?phone=01012345678 HTTP/1.1" 301 0
[2021-09-17 17:43:23] INFO [history] <QueryDict: {'phone': ['01012345678']}>
[2021-09-17 17:43:23] INFO "GET /history/?phone=01012345678 HTTP/1.1" 200 746
[2021-09-17 17:44:09] INFO [history] <QueryDict: {'phone': ['01012345678']}>
[2021-09-17 17:44:09] INFO "GET /history/?phone=01012345678 HTTP/1.1" 200 746
[2021-09-17 17:44:38] INFO [history] <QueryDict: {'phone': ['01012345678']}>
[2021-09-17 17:44:38] INFO "GET /history/?phone=01012345678 HTTP/1.1" 200 746
[2021-09-17 17:44:47] INFO [history] <QueryDict: {'phone': ['01012345678']}>
[2021-09-17 17:44:47] INFO "GET /history/?phone=01012345678 HTTP/1.1" 200 746
[2021-09-17 17:44:54] INFO [history] <QueryDict: {'phone': ['01012345678']}>
[2021-09-17 17:44:54] INFO "GET /history/?phone=01012345678 HTTP/1.1" 200 746
[2021-09-17 17:45:00] INFO [history] <QueryDict: {'phone': ['01012345678']}>
[2021-09-17 17:45:00] INFO "GET /history/?phone=01012345678 HTTP/1.1" 200 746
[2021-09-17 17:45:09] INFO [history] <QueryDict: {'phone': ['01012345678']}>
[2021-09-17 17:45:09] INFO "GET /history/?phone=01012345678 HTTP/1.1" 200 746
[2021-09-17 17:45:12] INFO [history] <QueryDict: {'phone': ['01012345678']}>
[2021-09-17 17:45:12] INFO "GET /history/?phone=01012345678 HTTP/1.1" 200 746
[2021-09-17 17:45:17] INFO [history] <QueryDict: {'phone': ['01012345678']}>
[2021-09-17 17:45:17] INFO "GET /history/?phone=01012345678 HTTP/1.1" 200 746
[2021-09-17 17:45:36] INFO [history] <QueryDict: {'phone': ['01012345678']}>
[2021-09-17 17:45:36] INFO "GET /history/?phone=01012345678 HTTP/1.1" 200 746
[2021-09-17 17:45:47] INFO [history] <QueryDict: {'phone': ['01012345678']}>
[2021-09-17 17:45:47] INFO "GET /history/?phone=01012345678 HTTP/1.1" 200 746
[2021-09-17 17:46:58] INFO "GET /admin/ HTTP/1.1" 200 8456
[2021-09-17 17:47:01] INFO "GET /admin/main/history/ HTTP/1.1" 200 8521
[2021-09-17 17:47:01] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 17:47:03] INFO "GET /admin/main/market/ HTTP/1.1" 200 7635
[2021-09-17 17:47:03] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 17:47:11] INFO "GET /admin/main/market/add/ HTTP/1.1" 200 10284
[2021-09-17 17:47:11] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 17:49:45] INFO [history] <QueryDict: {'phone': ['01012345678']}>
[2021-09-17 17:49:45] INFO "GET /history/?phone=01012345678 HTTP/1.1" 200 746
[2021-09-17 17:53:15] INFO [history] <QueryDict: {'phone': ['01012345678']}>
[2021-09-17 17:53:15] INFO "GET /history/?phone=01012345678 HTTP/1.1" 200 746
[2021-09-17 17:53:22] INFO [history] <QueryDict: {'phone': ['01012345678']}>
[2021-09-17 17:53:22] INFO "GET /history/?phone=01012345678 HTTP/1.1" 200 746
[2021-09-17 17:55:59] INFO [login] {'phone': '01052376809', 'password': 'xogns123'}
[2021-09-17 17:55:59] INFO "POST /login/ HTTP/1.1" 200 47
[2021-09-17 17:56:37] INFO [login] {'phone': '01012345678', 'password': 'qwer1234'}
[2021-09-17 17:56:37] INFO "POST /login/ HTTP/1.1" 200 47
[2021-09-17 17:56:59] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:57:02] INFO Watching for file changes with StatReloader
[2021-09-17 17:57:05] INFO "GET /admin/main/user/ HTTP/1.1" 200 8449
[2021-09-17 17:57:05] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 17:57:07] INFO "GET /admin/main/user/1/change/ HTTP/1.1" 200 11558
[2021-09-17 17:57:07] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 17:57:10] INFO "GET /admin/main/user/ HTTP/1.1" 200 8449
[2021-09-17 17:57:11] INFO "GET /admin/main/user/7/change/ HTTP/1.1" 200 11544
[2021-09-17 17:57:12] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 17:57:25] INFO [login] {'phone': '01092939495', 'password': 'qwer1234'}
[2021-09-17 17:57:25] INFO "POST /login/ HTTP/1.1" 200 58
[2021-09-17 17:58:20] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:58:22] INFO Watching for file changes with StatReloader
[2021-09-17 17:58:35] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:58:36] INFO Watching for file changes with StatReloader
[2021-09-17 17:58:40] INFO [login] {'phone': '01092939495', 'password': 'qwer1234'}
[2021-09-17 17:58:40] INFO "POST /login/ HTTP/1.1" 200 101
[2021-09-17 17:58:44] INFO "GET /barcode_user/0109293949574.png HTTP/1.1" 200 793
[2021-09-17 17:59:16] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 17:59:18] INFO Watching for file changes with StatReloader
[2021-09-17 17:59:24] INFO [login] {'phone': '01092939495', 'password': 'qwer1234'}
[2021-09-17 17:59:24] INFO "POST /login/ HTTP/1.1" 200 132
[2021-09-17 18:00:15] INFO /home/m0nd2y/paybag-server/paybag_api/main/views.py changed, reloading.
[2021-09-17 18:00:19] INFO Watching for file changes with StatReloader
[2021-09-17 18:00:22] INFO "GET /admin/ HTTP/1.1" 200 8456
[2021-09-17 18:00:24] INFO "GET /admin/main/market/ HTTP/1.1" 200 7635
[2021-09-17 18:00:24] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:01:41] INFO "GET /admin/main/market/add/ HTTP/1.1" 200 10284
[2021-09-17 18:01:41] INFO "GET /admin/main/market/add/ HTTP/1.1" 200 10284
[2021-09-17 18:01:41] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:01:42] INFO "GET /admin/main/market/ HTTP/1.1" 200 7635
[2021-09-17 18:01:42] INFO "GET /admin/main/market/ HTTP/1.1" 200 7635
[2021-09-17 18:01:43] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:01:44] INFO "GET /admin/main/market/add/ HTTP/1.1" 200 10284
[2021-09-17 18:01:45] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:02:19] INFO "POST /admin/main/market/add/ HTTP/1.1" 302 0
[2021-09-17 18:02:19] INFO "GET /admin/main/market/ HTTP/1.1" 200 8057
[2021-09-17 18:02:20] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:02:23] INFO "GET /admin/main/market/add/ HTTP/1.1" 200 10284
[2021-09-17 18:02:23] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:03:04] INFO "POST /admin/main/market/add/ HTTP/1.1" 302 0
[2021-09-17 18:03:05] INFO "GET /admin/main/market/ HTTP/1.1" 200 8272
[2021-09-17 18:03:05] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:04:14] INFO "GET /admin/main/market/add/ HTTP/1.1" 200 10284
[2021-09-17 18:04:14] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:04:43] INFO "POST /admin/main/market/add/ HTTP/1.1" 302 0
[2021-09-17 18:04:43] INFO "GET /admin/main/market/ HTTP/1.1" 200 8487
[2021-09-17 18:04:44] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:04:48] ERROR Internal Server Error: /history/
Traceback (most recent call last):
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'phone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/m0nd2y/paybag-server/paybag_api/main/views.py", line 187, in history
    search_phone = request.GET['phone']
  File "/home/m0nd2y/.local/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'phone'
[2021-09-17 18:04:49] ERROR "GET /history/ HTTP/1.1" 500 103167
[2021-09-17 18:04:58] INFO - Broken pipe from ('61.82.101.19', 57111)

[2021-09-17 18:05:00] INFO [market] request market data
[2021-09-17 18:05:00] INFO "GET /market/ HTTP/1.1" 200 2058
[2021-09-17 18:05:17] INFO - Broken pipe from ('61.82.101.19', 57115)

[2021-09-17 18:05:53] INFO "GET /admin/main/market/add/ HTTP/1.1" 200 10284
[2021-09-17 18:05:54] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:06:33] INFO "POST /admin/main/market/add/ HTTP/1.1" 302 0
[2021-09-17 18:06:33] INFO "GET /admin/main/market/ HTTP/1.1" 200 8702
[2021-09-17 18:06:34] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:07:05] INFO "GET /admin/main/market/add/ HTTP/1.1" 200 10284
[2021-09-17 18:07:05] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:07:31] INFO "POST /admin/main/market/add/ HTTP/1.1" 302 0
[2021-09-17 18:07:32] INFO "GET /admin/main/market/ HTTP/1.1" 200 8917
[2021-09-17 18:07:33] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:07:48] INFO "GET /admin/main/market/add/ HTTP/1.1" 200 10284
[2021-09-17 18:07:48] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:09:03] INFO "POST /admin/main/market/add/ HTTP/1.1" 302 0
[2021-09-17 18:09:04] INFO "GET /admin/main/market/ HTTP/1.1" 200 9132
[2021-09-17 18:09:04] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:09:06] INFO "GET /admin/main/market/add/ HTTP/1.1" 200 10284
[2021-09-17 18:09:07] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:10:18] INFO "POST /admin/main/market/add/ HTTP/1.1" 302 0
[2021-09-17 18:10:19] INFO "GET /admin/main/market/ HTTP/1.1" 200 9355
[2021-09-17 18:10:19] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:10:24] INFO [market] request market data
[2021-09-17 18:10:24] INFO "GET /market/ HTTP/1.1" 200 3335
[2021-09-17 18:10:40] INFO "GET /admin/main/market/add/ HTTP/1.1" 200 10284
[2021-09-17 18:10:40] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:11:40] INFO "POST /admin/main/market/add/ HTTP/1.1" 302 0
[2021-09-17 18:11:40] INFO "GET /admin/main/market/ HTTP/1.1" 200 9573
[2021-09-17 18:11:41] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:11:47] INFO [market] request market data
[2021-09-17 18:11:47] INFO "GET /market/ HTTP/1.1" 200 3663
[2021-09-17 18:12:03] INFO "GET /admin/main/market/add/ HTTP/1.1" 200 10284
[2021-09-17 18:12:03] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:13:06] INFO "POST /admin/main/market/add/ HTTP/1.1" 302 0
[2021-09-17 18:13:07] INFO "GET /admin/main/market/ HTTP/1.1" 200 9791
[2021-09-17 18:13:07] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:13:09] INFO "GET /admin/main/market/add/ HTTP/1.1" 200 10284
[2021-09-17 18:13:09] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:13:28] INFO [market] request market data
[2021-09-17 18:13:28] INFO "GET /market/ HTTP/1.1" 200 3973
[2021-09-17 18:14:19] INFO "POST /admin/main/market/add/ HTTP/1.1" 302 0
[2021-09-17 18:14:20] INFO "GET /admin/main/market/ HTTP/1.1" 200 10009
[2021-09-17 18:14:20] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:14:25] INFO [market] request market data
[2021-09-17 18:14:25] INFO "GET /market/ HTTP/1.1" 200 4281
[2021-09-17 18:14:39] INFO - Broken pipe from ('61.82.101.19', 57151)

[2021-09-17 18:14:43] INFO [market] request market data
[2021-09-17 18:14:43] INFO "GET /market/ HTTP/1.1" 200 4281
[2021-09-17 18:17:01] INFO [market] request market data
[2021-09-17 18:17:01] INFO "GET /market/ HTTP/1.1" 200 4281
[2021-09-17 18:17:58] INFO "GET /admin/main/market/add/ HTTP/1.1" 200 10284
[2021-09-17 18:17:58] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:18:40] INFO "POST /admin/main/market/add/ HTTP/1.1" 302 0
[2021-09-17 18:18:41] INFO "GET /admin/main/market/ HTTP/1.1" 200 10227
[2021-09-17 18:18:41] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:18:46] INFO [market] request market data
[2021-09-17 18:18:46] INFO "GET /market/ HTTP/1.1" 200 4595
[2021-09-17 18:18:57] INFO - Broken pipe from ('61.82.101.19', 57156)

[2021-09-17 18:19:24] INFO [market] request market data
[2021-09-17 18:19:24] INFO "GET /market/ HTTP/1.1" 200 4595
[2021-09-17 18:20:55] INFO "GET /admin/main/user/ HTTP/1.1" 200 8449
[2021-09-17 18:20:56] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:20:58] INFO "GET /admin/main/user/1/change/ HTTP/1.1" 200 11558
[2021-09-17 18:20:59] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:21:02] INFO "GET /admin/main/user/ HTTP/1.1" 200 8449
[2021-09-17 18:21:07] INFO "GET /admin/main/user/2/change/ HTTP/1.1" 200 11522
[2021-09-17 18:21:07] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:21:14] INFO "GET /admin/main/user/ HTTP/1.1" 200 8449
[2021-09-17 18:21:16] INFO "GET /admin/main/history/ HTTP/1.1" 200 8521
[2021-09-17 18:21:16] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:21:25] INFO "GET /admin/main/ecobag/ HTTP/1.1" 200 7420
[2021-09-17 18:21:26] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:21:28] INFO "GET /admin/main/ecobag/1/change/ HTTP/1.1" 200 10146
[2021-09-17 18:21:29] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[2021-09-17 18:24:16] INFO [market] request market data
[2021-09-17 18:24:16] INFO "GET /market/ HTTP/1.1" 200 4595
[2021-09-17 18:24:52] INFO [market] request market data
[2021-09-17 18:24:52] INFO "GET /market/ HTTP/1.1" 200 4595
